### ISSUE TITLE
undefined is not an object (evaluating 'PropTypes.oneOfType')

### ISSUE THREAD

**Issue by rachnbob** [JoeRoddy/react-native-leaderboard#1]
Shoud:
`import React, { Component, PropTypes } from 'react';`
be
`import React, { Component } from 'react';`
`import PropTypes from 'prop-types';`

**Comment by JoeRoddy** [comment]
Absolutely it should, guess this broke with a new version of RN or something.  Had no idea this was broken, thanks a ton!

Tested it and that change is working w/ RN 50 and also didn't break some of my older apps using 45.

Do you want to do the PR since you found it?

**Comment by JoeRoddy** [comment]
Closing, fixed in commit [830dc5418406eca17df86b2ae49c17a34b4c99c8](https://github.com/JoeRoddy/react-native-leaderboard/commit/830dc5418406eca17df86b2ae49c17a34b4c99c8).

Thanks @rachnbob !!
