### ISSUE TITLE
Trying to compile with create-react-app

### ISSUE THREAD

**Issue by pythonanonuser** [JoeRoddy/react-native-leaderboard#2]
I'm trying to use this package with create-react-app to create a leaderboard app. I tried using the line 
`import Leaderboard from 'react-native-leaderboard';`
in an empty App.js file and it's leading to the following error:

```
Failed to compile.

./node_modules/react-native-leaderboard/index.js
Module parse failed: Unexpected token (18:8)
You may need an appropriate loader to handle this file type.
| 
| export default class Leaderboard extends Component {
|   state = {
|     sortedData: []
|   };
```

I've tried configuring my .babelrc file to include the following:
```
{
    "presets": ["env", "react"],
    "plugins": ["transform-class-properties"]
}
```

Any idea what might be wrong?

**Comment by agpmilli** [comment]
Exact same issue here

**Comment by JoeRoddy** [comment]
I'll take a look, thanks for the heads up.

**Comment by JoeRoddy** [comment]
Are you sure you used create-react-native-app and not create-react-app on accident @pythonanonuser 

I got the same error output with create-react-app, but this is a component for React Native, not a react web app.

I was able to get it working with this example: 
```
import React from "react";
import { StyleSheet, Text, View } from "react-native";
import Leaderboard from "react-native-leaderboard";

export default class App extends React.Component {
  state = {
    data: []
  };

  componentDidMount() {
    let data = [];
    for (let i = 0; i < 25; i++) {
      data.push({ name: "UserName", score: Math.random() * 100 });
    }
    this.setState({ data });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={{ padding: 30 }}>Example Header</Text>
        <Leaderboard data={this.state.data} sortBy="score" labelBy="name" />
      </View>
    );
  }
}
```

**Comment by JoeRoddy** [comment]
You might be able to get it working on a web app with this: https://github.com/necolas/react-native-web

**Comment by agpmilli** [comment]
> Are you sure you used create-react-native-app and not create-react-app on accident

This was my problem. No way to use it with create-react-app ?
Thanks

**Comment by JoeRoddy** [comment]
@agpmilli You could try react-native-web, I haven't used it, so no promises that it will work.  You can also view the source [here](https://github.com/JoeRoddy/react-native-leaderboard/blob/master/index.js), it's only one file.  You could create your own web component and replace the View components with divs, remove the Text components, etc.

**Comment by pythonanonuser** [comment]
@agpmilli @JoeRoddy I'm pretty new to this so might need some specific guidance. I'd like to use create-react-app for deployment if possible, as it handles the webpack and babel stuff fairly well. For some reason it's not liking the syntax in the file, as even when I add a constructor to the class to deal with the error around `state = {` I still get an error on the next line at the `static` command. Any ideas? 

I believe I'm running the latest release of create-react-app. I installed using `npm install -g create-react-app` as instructed to on the website, but not sure how to verify version.

**Comment by JoeRoddy** [comment]
@pythonanonuser  No worries!! Are you trying to create a web application or a mobile application?  This project is for mobile applications built with **React Native** (for mobile apps).  As such, if you want to use it, you'd have to create your project with [create-react-native-app](https://facebook.github.io/react-native/blog/2017/03/13/introducing-create-react-native-app.html) instead of create-react-app.

**Comment by pythonanonuser** [comment]
@JoeRoddy Thanks for the clarification, didn't realize this was meant for react native.
