### ISSUE TITLE
Error: ReferenceError: assignment to undeclared variable _sort

### ISSUE THREAD

**Issue by chellem** [JoeRoddy/react-native-leaderboard#6]
Got this error when testing with the [examples](https://github.com/JoeRoddy/react-native-leaderboard/tree/master/examples)

How to resolve it?

**Comment by sweih** [comment]
Same error when trying to use the component.

**Comment by geekmiester** [comment]
is this solved yet? Here for same error

**Comment by dre2004** [comment]
I submitted a pull request to fix it, if you want to fix it locally edit the index.js at the bottom of the file there is a 

_sort = ...

change that to 

const _sort = ...

**Comment by vivekkj123** [comment]
@JoeRoddy At least merge the PR and release updated version. Without merging this PR, this NPM module is useless and in grave stage.

**Comment by vivekkj123** [comment]
Thanks JoeRoddy ❤️
